### PR TITLE
'skysim' loop over sources in scene.ini added

### PR DESCRIPTION
**Pull request by toastmaker**
'skysim' version of the loop over sources from scene.ini.

It seems it works.

radius arbitrary so far r=10.

Do you know how to add 'labels' ?

### CODE REVIEW

**Comment by toastmaker** [comment]
modified Pixels to Sky for coordinates from scene.ini

**Comment by skendrew** [comment]
looks good thanks - but this hasn't been merged yet right? I don't see your code in my master branch.

**Comment by toastmaker** [comment]
should you not approve the merge first? I don't remember the exact workflow details.
m

**Comment by skendrew** [comment]
yes - but I had to reopen the pull request first. done now! since this uses a mirisim tool, I presume this now also has to be run in the mirisim environment to work? I can add a note in the README for that.

**Comment by toastmaker** [comment]
Now I see. I closed the pull request by mistake last night, I was not sure if one needs to finish it and then submit. I'll be smarter next time.

Yes, it requires Skysim for the loop over the sources, therefore mirisim env is good to have.

I did it by

conda install -c astropy regions

in the mirisim environment (as suggested on https://astropy-regions.readthedocs.io/en/latest/installation.html)

**Pull request merged**
